version: '3.7'
services:
  authorization-server:
    container_name: authorization-server
    image: adoptopenjdk:11.0.10_9-jdk-openj9-0.24.0
    volumes:
      - './authorization-server/build/libs/authorization-server-1.0.0-SNAPSHOT.jar:/var/authorization/authorization-server.jar'
    ports:
      - "8084:8084"
    command: "java -Xmx128m -Xms128m -Dfile.encoding=UTF-8 -Duser.timezone=GMT+9 -Dspring.profiles.active=prod,log -jar /var/authorization/authorization-server.jar"
    links:
      - maraidb
      - redis
  maraidb:
    container_name: authorization-mariadb
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=authorization
      - MYSQL_USER=authorization
      - MYSQL_PASSWORD=1234
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql
      - ./docker/mariadb/conf.d:/etc/mysql/conf.d
      - "./src/main/resources/schema/init-docker.sql:/docker-entrypoint-initdb.d/init.sql"
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
  redis:
    container_name: authorization-redis
    image: redis:latest
    command: redis-server --requirepass 1234 --port 6379
    ports:
      - "6379:6379"
    labels:
      - "name=redis"
      - "mode=standalone"