# Production profile
logging:
  file:
    path: /var/authorization-server/logs
  level:
    io.github.syakuis: info
    org.springframework.security: trace
spring:
  main:
    banner-mode: log
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authorization
    username: authorization
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: schema/import-mysql.sql