logging:
  level:
    org.springframework.security: trace
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        hbm2ddl:
          import_files: schema/import-h2.sql
