logging:
  file:
    name: authorization.log
    path:
  logback:
    rollingpolicy:
      clean-history-on-start: false
      max-file-size: 10MB
      total-size-cap: 20GB
      max-history: 30
  level:
    root: info
    io.github.syakuis: trace
    org.springframework.web: info
    org.springframework.security: info
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: off
server:
  port: 8080
  forward-headers-strategy: native
spring:
  application:
    name: authorization-server
  config:
    import: classpath:properties/authorization-server.yml, classpath:properties/resource-server.yml
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    hikari:
      max-lifetime: 600000
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  redis:
    host: localhost
    port: 6379
    password: 1234
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
  mvc:
    log-request-details: false