# Develop or Default profile
debug: false
trace: false
logging:
  level:
    root: info
    io.github.syakuis: trace
    org.springframework: info
    org.springframework.web: debug
    org.springframework.security: trace
server:
  port: 8080
spring:
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true
  config:
    import: classpath:properties/resource-server.yml