### 암호 방식 액세스 토큰 교환
POST http://localhost:8080/oauth/token?grant_type=password&username=test&password=1234
Authorization: Basic 5f4896080ecee6c7817c68afaf634b04ec74e9ccccd9b64a69845284ef36ff4fdb97480deaae1535 dUd6N3ojXSI0dGVseUwy
Content-Type: application/x-www-form-urlencoded

### 액세스 토큰 검증
POST http://localhost:8080/oauth/check_token?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjN2I3ODJiNS1mOGI1LTExZWItOTcyZi0wMmEyMDg1MDZiZDYiLCJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOm51bGwsImF1ZCI6WyIiXSwidXNlcl9uYW1lIjoidGVzdCIsInNjb3BlIjpbInJlYWQiXSwibmFtZSI6Iu2FjOyKpO2KuCIsImV4cCI6MTYzNDg3MzM1MywianRpIjoiMGFlZDU4MzAtNTYzYi00MzRlLWI0MTUtZTJjODYzMTE3NDFmIiwiY2xpZW50X2lkIjoiNWY0ODk2MDgwZWNlZTZjNzgxN2M2OGFmYWY2MzRiMDRlYzc0ZTljY2NjZDliNjRhNjk4NDUyODRlZjM2ZmY0ZmRiOTc0ODBkZWFhZTE1MzUifQ.GfhN9Dplz83x3sCg7R6F4DwDG2nhrPqCo_GJZUzfn4v3qD7RUGgs6gmZ6DfeSDGa72iJbtkN3vcxwadCo4E_iiyf2h747EhIz-kj2vaV3jBlV98sUph5khR_mXqf7EdTWfqQHfQWEC6C2_ChOxt2xq9YK-AgnGXpYAo1bODPlFFBav52luQ6IfyEc3gYBqIaJ-ggJnB3p-IZRXeACbNc6LQrNlXXH_IDQcdfSAPkNPyAZp_M-enG8MVXpSm6g9PdwOtD3-Nj5hYD6QQrfru16-7QzdlV_tQK86eVVoQIFA6HDXD_L1OLmVaXl7qvmSW7brI8IJ4MCFfAmj9yJ2oWsQ
Authorization: Basic 5f4896080ecee6c7817c68afaf634b04ec74e9ccccd9b64a69845284ef36ff4fdb97480deaae1535 dUd6N3ojXSI0dGVseUwy
Content-Type: application/x-www-form-urlencoded

### 액세스 토큰 삭제 (테스트용)
DELETE http://localhost:8080/oauth2/v1/token/delete/eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjN2I3ODJiNS1mOGI1LTExZWItOTcyZi0wMmEyMDg1MDZiZDYiLCJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOm51bGwsImF1ZCI6WyIiXSwidXNlcl9uYW1lIjoidGVzdCIsInNjb3BlIjpbInJlYWQiXSwibmFtZSI6Iu2FjOyKpO2KuCIsImV4cCI6MTYzNDg3Mzg3NywianRpIjoiYWEzODUwZjYtZjk3ZS00ODhhLWFjYmEtM2M4Y2I4NGViOTVkIiwiY2xpZW50X2lkIjoiNWY0ODk2MDgwZWNlZTZjNzgxN2M2OGFmYWY2MzRiMDRlYzc0ZTljY2NjZDliNjRhNjk4NDUyODRlZjM2ZmY0ZmRiOTc0ODBkZWFhZTE1MzUifQ.jNYZ_6rdjKhfZZJJio756fZVqQmYU4PMLr52kgVA2EwgFtZcACLf-9fMe3vZbuLETk3O0nM-2KYDkNJfqkrS6aYHn5iyYv2kBPlnNh7xZSfnl-zFKCO980UVALxSsBu9xlf70UC0CESoxAlQ56I_N5-YK8RjF4BjZ5ROiq8zPXT_vvYIFJ8VLmGpfJFvnRL0L2gvg4WlKp0rOxbXO-1Pt1EevB2MvAnaT_DyDz9gZwebWwC8-okWvR5qCZsWvLv2nlVV1Yv8RYfYxu1OwcEBjP7CO1f9-I0FKWOVNXbB9MlS2Q-uuCzjTg1jMtTU5pr6IxYZl9fH_ffcDSliA8r7kQ