### 애플리케이션 등록
POST http://localhost:8081/client-registrations
Content-Type: application/json

{
  "resourceIds" : null,
  "scopes" : [ "read" ],
  "authorizedGrantTypes" : [ "password" ],
  "webServerRedirectUri" : null,
  "authorities" : null,
  "accessTokenValidity" : 1000,
  "refreshTokenValidity" : 2000,
  "additionalInformation" : null,
  "autoApprove" : null
}

> {% client.global.set("client_id", response.body.clientId); client.global.set("client_secret", response.body.clientSecret); %}

### 애플리케이션 제거
DELETE http://localhost:8081/client-registrations/{{client_id}}