### 액세스 토큰 검증
POST http://localhost:8080/oauth/check_token?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjN2I3ODJiNS1mOGI1LTExZWItOTcyZi0wMmEyMDg1MDZiZDYiLCJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOm51bGwsImF1ZCI6WyIiXSwidXNlcl9uYW1lIjoidGVzdCIsInNjb3BlIjpbInJlYWQiXSwibmFtZSI6Iu2FjOyKpO2KuCIsImV4cCI6MTYzNDg3MzM1MywianRpIjoiMGFlZDU4MzAtNTYzYi00MzRlLWI0MTUtZTJjODYzMTE3NDFmIiwiY2xpZW50X2lkIjoiNWY0ODk2MDgwZWNlZTZjNzgxN2M2OGFmYWY2MzRiMDRlYzc0ZTljY2NjZDliNjRhNjk4NDUyODRlZjM2ZmY0ZmRiOTc0ODBkZWFhZTE1MzUifQ.GfhN9Dplz83x3sCg7R6F4DwDG2nhrPqCo_GJZUzfn4v3qD7RUGgs6gmZ6DfeSDGa72iJbtkN3vcxwadCo4E_iiyf2h747EhIz-kj2vaV3jBlV98sUph5khR_mXqf7EdTWfqQHfQWEC6C2_ChOxt2xq9YK-AgnGXpYAo1bODPlFFBav52luQ6IfyEc3gYBqIaJ-ggJnB3p-IZRXeACbNc6LQrNlXXH_IDQcdfSAPkNPyAZp_M-enG8MVXpSm6g9PdwOtD3-Nj5hYD6QQrfru16-7QzdlV_tQK86eVVoQIFA6HDXD_L1OLmVaXl7qvmSW7brI8IJ4MCFfAmj9yJ2oWsQ
Authorization: Basic 5f4896080ecee6c7817c68afaf634b04ec74e9ccccd9b64a69845284ef36ff4fdb97480deaae1535 dUd6N3ojXSI0dGVseUwy
Content-Type: application/x-www-form-urlencoded

### 액세스 토큰 삭제 (테스트용)
DELETE http://localhost:8080/oauth2/v1/token
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjN2I3ODJiNS1mOGI1LTExZWItOTcyZi0wMmEyMDg1MDZiZDYiLCJhZGRpdGlvbmFsSW5mb3JtYXRpb24iOm51bGwsInVzZXJfbmFtZSI6InRlc3QiLCJzY29wZSI6WyJyZWFkIl0sIm5hbWUiOiLthYzsiqTtirgiLCJleHAiOjE2MzU0NzgwMzIsImp0aSI6ImFhMDI1MmYwLWIxMDktNGRlYS1hMGM3LWEwY2FkM2YyN2YyOSIsImNsaWVudF9pZCI6IjVmNDg5NjA4MGVjZWU2Yzc4MTdjNjhhZmFmNjM0YjA0ZWM3NGU5Y2NjY2Q5YjY0YTY5ODQ1Mjg0ZWYzNmZmNGZkYjk3NDgwZGVhYWUxNTM1In0.FeuWp6pvehUrfz6kUzoIUlrzifq8Dh7r6g9Rin88PuXrA7iAN3kJ6UA0wS9wXhtXSRbQiuaECyvHcxopI2HH7mPyKa9pNQzTb-I9JzhClf8U5_H_TUJM6bYJq3MI_13Pi185wfUuBIJJWsi4o2UbJobAFioA6u-jIBjKoK0HaFbK22Cuh-taywWyObnpH8Bpj7pempAQYHP_idi6NoAt5ppnWR20ol-U30sntrxNkh8ReSEI8VYWscRa5R87dpLWIzfC-Vo-ZeLVv7lnbu4lC8l5NHOCnek-yB6ylqF6QyH9ORpNnkunR1ln6DWpL0S2AyPk65Kclj0QGEGX2hAeJA