### 암호 방식 액세스 토큰 교환
POST http://localhost:8080/oauth/token?grant_type=password&username=test&password=1234
Authorization: Basic 5f4896080ecee6c7817c68afaf634b04ec74e9ccccd9b64a69845284ef36ff4fdb97480deaae1535 dUd6N3ojXSI0dGVseUwy
Content-Type: application/x-www-form-urlencoded