-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 14:52:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authorization` DEFAULT CHARACTER SET utf8 ;
USE `authorization` ;


-- -----------------------------------------------------
-- Table `oauth_access_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth_access_token` (
                                                    `authentication_id` VARCHAR(255) NOT NULL,
                                                    `token_id` VARCHAR(255) NOT NULL,
                                                    `token` BLOB NOT NULL,
                                                    `user_name` VARCHAR(255) NOT NULL,
                                                    `client_id` VARCHAR(255) NULL,
                                                    `authentication` BLOB NOT NULL,
                                                    `refresh_token` VARCHAR(255) NULL,
                                                    PRIMARY KEY (`authentication_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_client_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth_client_details` (
                                                      `client_id` VARCHAR(255) NOT NULL,
                                                      `resource_ids` VARCHAR(255) NULL,
                                                      `client_secret` VARCHAR(255) NOT NULL,
                                                      `scop` VARCHAR(255) NULL,
                                                      `authorized_grant_types` VARCHAR(255) NULL,
                                                      `web_server_redirect_uri` VARCHAR(255) NULL,
                                                      `authorities` VARCHAR(255) NULL,
                                                      `access_token_validity` INT NULL,
                                                      `refresh_token_validity` INT NULL,
                                                      `additional_information` VARCHAR(4096) NULL,
                                                      `autoapprove` VARCHAR(255) NULL,
                                                      PRIMARY KEY (`client_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_client_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth_client_token` (
                                                    `authentication_id` VARCHAR(255) NOT NULL,
                                                    `token_id` VARCHAR(255) NOT NULL,
                                                    `token` BLOB NOT NULL,
                                                    `user_name` VARCHAR(255) NOT NULL,
                                                    `client_id` VARCHAR(255) NOT NULL,
                                                    PRIMARY KEY (`authentication_id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oauth_refresh_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth_refresh_token` (
                                                     `token_id` VARCHAR(255) NOT NULL,
                                                     `token` BLOB NOT NULL,
                                                     `authentication` BLOB NOT NULL,
                                                     PRIMARY KEY (`token_id`))
    ENGINE = InnoDB;