-- MySQL Script generated by MySQL Workbench
-- Tue Jul 16 14:52:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema authorization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authorization` DEFAULT CHARACTER SET utf8 ;
USE `authorization` ;


-- -----------------------------------------------------
-- Table `member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member` (
                                        `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '회원 번호',
                                        `username` VARCHAR(100) NOT NULL COMMENT '계정',
                                        `name` VARCHAR(45) NOT NULL COMMENT '이름',
                                        `password` VARCHAR(150) NOT NULL COMMENT '암호',
                                        `creation_datetime` DATETIME NULL COMMENT '등록일',
                                        `modification_datetime` DATETIME NULL COMMENT '수정일',
                                        `disabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '계정 비활성화',
                                        `locked` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '계정 차단',
                                        `deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '삭제여부',
                                        PRIMARY KEY (`id`),
                                        UNIQUE INDEX `username_uq` (`username` ASC),
                                        INDEX `fk_member_deleted` (`deleted` ASC))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `member_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `member_role` (
                                             `member_id` BIGINT(20) NOT NULL,
                                             `role_id` INT(11) NOT NULL,
                                             INDEX `fk_member_role_role_idx` (`role_id` ASC),
                                             PRIMARY KEY (`member_id`, `role_id`),
                                             CONSTRAINT `fk_member_role_member`
                                                 FOREIGN KEY (`member_id`)
                                                     REFERENCES `member` (`id`)
                                                     ON DELETE NO ACTION
                                                     ON UPDATE NO ACTION,
                                             CONSTRAINT `fk_member_role_role`
                                                 FOREIGN KEY (`role_id`)
                                                     REFERENCES `role` (`id`)
                                                     ON DELETE NO ACTION
                                                     ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role` (
                                      `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '역할 id',
                                      `name` VARCHAR(45) NOT NULL COMMENT '역할명',
                                      `disabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '사용여부',
                                      PRIMARY KEY (`id`),
                                      UNIQUE INDEX `roleName_UNIQUE` (`name` ASC))
    ENGINE = InnoDB
    COMMENT = '역할';


-- -----------------------------------------------------
-- Table `role_hierarchy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `role_hierarchy` (
                                                `role_id` INT(11) NOT NULL,
                                                `role_child_id` INT(11) NOT NULL,
                                                PRIMARY KEY (`role_id`, `role_child_id`),
                                                INDEX `fk_role_hierarchy_role2_idx` (`role_child_id` ASC),
                                                INDEX `fk_role_hierarchy_role1_idx` (`role_id` ASC),
                                                CONSTRAINT `fk_role_hierarchy_role2`
                                                    FOREIGN KEY (`role_child_id`)
                                                        REFERENCES `role` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION,
                                                CONSTRAINT `fk_role_hierarchy_role1`
                                                    FOREIGN KEY (`role_id`)
                                                        REFERENCES `role` (`id`)
                                                        ON DELETE NO ACTION
                                                        ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
