@startuml
skinparam shadowing false
title Client Credentials Grant Type
actor "Resource Owner" as user
participant "Application" as fb
participant "Application Server (BFF)" as bff
participant "Authorization Server" as auth

user -> fb: Login Start
fb -> auth: AccessToken request
note right
POST /oauth/token?grant_type=client_credential
Authorization: Basic ClientId:ClientSecret
end note
fb <-- auth: AccessToken response
user <-- fb: Login End
@enduml