@startuml
skinparam shadowing false
title Password Grant Type
actor "Resource Owner" as user
participant "Frontend" as fb
participant "Application Server (BFF)" as bff
participant "Authorization Server" as auth

user -> fb: Login Start
fb -> bff: Login request
note right
POST /oauth/token?grant_type=password&username=test&password=1234
end note
bff -> auth: AccessToken request
note right
POST /oauth/token?grant_type=password&username=test&password=1234
Authorization: Basic ClientId:ClientSecret
end note
bff <-- auth: AccessToken response
fb <-- bff: Login response
user <-- fb: Login End
@enduml