# Production profile
logging:
  file:
    path: /var/syakuis/account/logs
  level:
    io.github.syakuis: info
spring:
  main:
    banner-mode: log
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/authorization
    username: authorization
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect